from __future__ import annotations

import re
import unicodedata
import xml.etree.ElementTree as ET

from .models import (
    BlockKind,
    EditorialSourceKind,
    InlineKind,
    InlineNode,
    ParagraphCategory,
    ParsedBlock,
    ParsedDocument,
)
from .pandoc_parser import inline_text
from .style_registry import WordStyleRegistry, normalize_style_name


TEI_NS = "http://www.tei-c.org/ns/1.0"
XML_NS = "http://www.w3.org/XML/1998/namespace"
ET.register_namespace("", TEI_NS)


def _tei(tag: str) -> str:
    return f"{{{TEI_NS}}}{tag}"


def _append_text(parent: ET.Element, last_child: ET.Element | None, text: str) -> None:
    if not text:
        return
    if last_child is None:
        parent.text = (parent.text or "") + text
    else:
        last_child.tail = (last_child.tail or "") + text


class NoticeTeiBuilder:
    def __init__(self, style_registry: WordStyleRegistry | None = None) -> None:
        self._styles = style_registry or WordStyleRegistry()

    def build_document_xml(
        self,
        document: ParsedDocument,
        *,
        source_kind: EditorialSourceKind = EditorialSourceKind.PLAY_NOTICE,
    ) -> str:
        title = self._extract_main_title(document)
        subtitle = self._extract_sub_title(document)
        slug = _slugify(title or document.source_path.stem)
        root_div_type, root_id_suffix = _root_div_spec(source_kind)

        tei = ET.Element(_tei("TEI"))
        header = ET.SubElement(tei, _tei("teiHeader"))
        file_desc = ET.SubElement(header, _tei("fileDesc"))
        title_stmt = ET.SubElement(file_desc, _tei("titleStmt"))
        ET.SubElement(title_stmt, _tei("title")).text = title or "Notice editoriale"
        publication_stmt = ET.SubElement(file_desc, _tei("publicationStmt"))
        ET.SubElement(publication_stmt, _tei("p")).text = "Generated by Ekdosis-TEI Studio notice import"
        source_desc = ET.SubElement(file_desc, _tei("sourceDesc"))
        ET.SubElement(source_desc, _tei("p")).text = "Imported from a styled Word document."

        text = ET.SubElement(tei, _tei("text"))
        body = ET.SubElement(text, _tei("body"))
        notice = ET.SubElement(
            body,
            _tei("div"),
            {"type": root_div_type, f"{{{XML_NS}}}id": f"{slug}-{root_id_suffix}"},
        )
        ET.SubElement(notice, _tei("head"), {"type": "main"}).text = title or document.source_path.stem
        if subtitle:
            ET.SubElement(notice, _tei("head"), {"type": "sub"}).text = subtitle

        stack: list[tuple[int, ET.Element]] = [(0, notice)]
        bibliography_level: int | None = None
        bibliography_list: ET.Element | None = None

        for block in document.blocks:
            if block.kind is BlockKind.UNSUPPORTED:
                continue
            if self._is_title_like_block(block):
                continue

            if block.kind is BlockKind.HEADING:
                level = block.heading_level or 1
                while stack and stack[-1][0] >= level:
                    stack.pop()
                parent = stack[-1][1] if stack else notice
                section = ET.SubElement(parent, _tei("div"), {"type": _heading_div_type(level)})
                head = ET.SubElement(section, _tei("head"))
                self._append_inlines(head, block.inlines)
                stack.append((level, section))

                heading_text = normalize_style_name(inline_text(block.inlines))
                if heading_text == "bibliographie":
                    bibliography_level = level
                    bibliography_list = ET.SubElement(section, _tei("listBibl"))
                else:
                    bibliography_level = None
                    bibliography_list = None
                continue

            container = stack[-1][1] if stack else notice
            is_biblio_entry = (
                bibliography_level is not None
                and bibliography_list is not None
                and block.kind is BlockKind.PARAGRAPH
                and self._paragraph_category(block) in {ParagraphCategory.PARA, ParagraphCategory.PARA_NOINDENT}
            )
            if is_biblio_entry:
                content = inline_text(block.inlines).strip()
                if content:
                    bibl = ET.SubElement(bibliography_list, _tei("bibl"))
                    self._append_inlines(bibl, block.inlines)
                continue

            self._append_content_block(container, block)

        tree = ET.ElementTree(tei)
        ET.indent(tree, "  ")
        return ET.tostring(tei, encoding="utf-8", xml_declaration=True).decode("utf-8")

    def _append_content_block(self, parent: ET.Element, block: ParsedBlock) -> None:
        if block.kind is BlockKind.LIST:
            list_attrs = {"type": "ordered"} if block.ordered_list else {"type": "unordered"}
            listing = ET.SubElement(parent, _tei("list"), list_attrs)
            for item in block.list_items:
                node = ET.SubElement(listing, _tei("item"))
                self._append_inlines(node, item)
            return

        if block.kind is BlockKind.TABLE:
            if block.table_complex_reason:
                return
            table = ET.SubElement(parent, _tei("table"))
            for raw_row in block.table_rows:
                row = ET.SubElement(table, _tei("row"))
                for cell_runs in raw_row:
                    cell = ET.SubElement(row, _tei("cell"))
                    self._append_inlines(cell, cell_runs)
            return

        if block.kind is not BlockKind.PARAGRAPH:
            return

        category = self._paragraph_category(block)
        if category is ParagraphCategory.BLOCK_QUOTE:
            quote = ET.SubElement(parent, _tei("quote"))
            paragraph = ET.SubElement(quote, _tei("p"))
            self._append_inlines(paragraph, block.inlines)
            return

        attrs: dict[str, str] = {}
        if category is ParagraphCategory.PARA_NOINDENT:
            attrs["rend"] = "noindent"
        if category is ParagraphCategory.CAPTION:
            attrs["type"] = "caption"
        paragraph = ET.SubElement(parent, _tei("p"), attrs)
        self._append_inlines(paragraph, block.inlines)

    def _append_inlines(self, parent: ET.Element, runs: tuple[InlineNode, ...]) -> None:
        last_child: ET.Element | None = None
        for run in runs:
            if run.kind is InlineKind.TEXT:
                _append_text(parent, last_child, run.text)
                continue

            if run.kind is InlineKind.NOTE:
                note = ET.SubElement(parent, _tei("note"), {"place": "foot"})
                self._append_inlines(note, run.children)
                last_child = note
                continue

            if run.kind is InlineKind.LINK:
                attrs = {"target": run.target or "#"}
                ref = ET.SubElement(parent, _tei("ref"), attrs)
                self._append_inlines(ref, run.children)
                last_child = ref
                continue

            rend = _inline_rend(run.kind)
            hi = ET.SubElement(parent, _tei("hi"), {"rend": rend})
            self._append_inlines(hi, run.children)
            last_child = hi

    def _extract_main_title(self, document: ParsedDocument) -> str:
        for block in document.blocks:
            if block.kind is BlockKind.PARAGRAPH and self._paragraph_category(block) is ParagraphCategory.DOC_TITLE:
                return inline_text(block.inlines).strip()
        return ""

    def _extract_sub_title(self, document: ParsedDocument) -> str:
        for block in document.blocks:
            if block.kind is BlockKind.PARAGRAPH and self._paragraph_category(block) is ParagraphCategory.DOC_SUBTITLE:
                return inline_text(block.inlines).strip()
        return ""

    def _is_title_like_block(self, block: ParsedBlock) -> bool:
        if block.kind is not BlockKind.PARAGRAPH:
            return False
        category = self._paragraph_category(block)
        return category in {ParagraphCategory.DOC_TITLE, ParagraphCategory.DOC_SUBTITLE}

    def _paragraph_category(self, block: ParsedBlock) -> ParagraphCategory:
        style_name = (block.style_name or "Normal").strip()
        resolution = self._styles.resolve_style_category(style_name)
        if resolution is None:
            return ParagraphCategory.PARA
        return resolution.category


def _inline_rend(kind: InlineKind) -> str:
    if kind is InlineKind.ITALIC:
        return "italic"
    if kind is InlineKind.BOLD:
        return "bold"
    if kind is InlineKind.UNDERLINE:
        return "underline"
    if kind is InlineKind.SMALLCAPS:
        return "smallcaps"
    if kind is InlineKind.SUP:
        return "sup"
    if kind is InlineKind.SUB:
        return "sub"
    if kind is InlineKind.STRIKETHROUGH:
        return "strikethrough"
    return "inline"


def _heading_div_type(level: int) -> str:
    if level == 1:
        return "section"
    if level == 2:
        return "subsection"
    if level == 3:
        return "subsubsection"
    return "level4"


def _slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value.strip())
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_only).strip("-")
    return slug or "notice"


def _root_div_spec(source_kind: EditorialSourceKind) -> tuple[str, str]:
    if source_kind is EditorialSourceKind.HOME_PAGE:
        return "accueil", "accueil"
    if source_kind is EditorialSourceKind.GENERAL_INTRO:
        return "introduction-generale", "introduction-generale"
    if source_kind is EditorialSourceKind.PLAY_PREFACE:
        return "preface", "preface"
    return "notice", "notice"
