from __future__ import annotations

from pathlib import Path

from ets.application.site_publication_config import SitePublicationDialogConfig
from ets.latex.castlist_from_tei import tei_castlist_to_latex
from ets.latex.ekdosis_from_tei import tei_to_ekdosis
from ets.latex.escaping import escape_latex_text
from ets.latex.standard_from_tei import tei_peritext_to_latex
from ets.latex.templates import render_ekdosis_support_preamble


def render_publication_pdf_master(config: SitePublicationDialogConfig) -> str:
    lines: list[str] = [
        "% Provisional publication PDF master generated by Ekdosis-TEI Studio.",
        "% This file is an internal build artifact for the future complete publication PDF.",
        r"\documentclass{book}",
        r"\usepackage[main=french,spanish,latin]{babel}",
        r"\usepackage{fontspec}",
        r"\usepackage{csquotes}",
        render_ekdosis_support_preamble(),
        "",
        rf"\title{{{_latex_text(config.corpus_title or 'Edition')}}}",
        rf"\author{{{_latex_text(config.author_name)}}}",
        r"\date{}",
        "",
        r"\begin{document}",
        r"\frontmatter",
        r"\maketitle",
    ]

    if config.scientific_editor.strip():
        lines.extend(
            [
                "",
                rf"\noindent Responsable scientifique : {_latex_text(config.scientific_editor)}",
            ]
        )

    lines.extend(["", r"\mainmatter"])

    if config.general_intro_tei is not None:
        lines.extend(
            [
                "",
                r"\chapter*{Introduction generale}",
                f"% GENERAL INTRO: {_path_comment(config.general_intro_tei)}",
                _peritext_fragment(config.general_intro_tei),
            ]
        )

    for play in config.plays:
        label = play.play_slug.strip() or play.dramatic_xml_path.stem
        lines.extend(
            [
                "",
                rf"\chapter{{{_latex_text(label)}}}",
                f"% PLAY: {_latex_text(label)}",
            ]
        )

        if play.notice_xml_path is not None:
            lines.extend(
                [
                    "",
                    r"\section*{Notice}",
                    f"% NOTICE: {_path_comment(play.notice_xml_path)}",
                    _peritext_fragment(play.notice_xml_path),
                ]
            )

        if play.preface_xml_path is not None:
            lines.extend(
                [
                    "",
                    r"\section*{Preface}",
                    f"% PREFACE: {_path_comment(play.preface_xml_path)}",
                    _peritext_fragment(play.preface_xml_path),
                ]
            )

        lines.extend(
            [
                "",
                r"\section*{Dramatis personae}",
                _dramatis_comment(play.dramatis_xml_path, play.dramatic_xml_path),
                _dramatis_fragment(play.dramatis_xml_path, play.dramatic_xml_path),
                "",
                r"\section*{Texte dramatique}",
                f"% DRAMATIC TEXT: {_path_comment(play.dramatic_xml_path)}",
                _dramatic_fragment(play.dramatic_xml_path),
            ]
        )

    lines.extend(["", r"\end{document}", ""])
    return "\n".join(lines)


def _latex_text(value: str) -> str:
    return escape_latex_text(value.strip())


def _path_comment(path: Path) -> str:
    return str(path.resolve())


def _peritext_fragment(path: Path) -> str:
    return tei_peritext_to_latex(path).rstrip()


def _dramatis_comment(dramatis_xml_path: Path | None, dramatic_xml_path: Path) -> str:
    if dramatis_xml_path is not None:
        return f"% DRAMATIS PERSONAE: {_path_comment(dramatis_xml_path)}"
    return f"% DRAMATIS PERSONAE: front of {_path_comment(dramatic_xml_path)}"


def _dramatis_fragment(dramatis_xml_path: Path | None, dramatic_xml_path: Path) -> str:
    source_path = dramatis_xml_path if dramatis_xml_path is not None else dramatic_xml_path
    return tei_castlist_to_latex(source_path).rstrip()


def _dramatic_fragment(dramatic_xml_path: Path) -> str:
    fragment = tei_to_ekdosis(dramatic_xml_path, standalone=False).rstrip()
    if not fragment:
        return r"\begin{ekdosis}" + "\n" + r"\end{ekdosis}"
    return "\\begin{ekdosis}\n" + fragment + "\n\\end{ekdosis}"
