from __future__ import annotations

from pathlib import Path

from lxml import etree

from ets.application.site_publication_config import SitePublicationDialogConfig
from ets.latex.castlist_from_tei import tei_castlist_to_latex
from ets.latex.escaping import escape_latex_text
from ets.latex.reledmac_from_tei import tei_to_reledmac
from ets.latex.reledmac_templates import render_reledmac_support_preamble
from ets.latex.standard_from_tei import tei_peritext_to_latex


def render_publication_pdf_master(config: SitePublicationDialogConfig) -> str:
    lines: list[str] = [
        "% Provisional publication PDF master generated by Ekdosis-TEI Studio.",
        "% This file is an internal build artifact for the future complete publication PDF.",
        render_purh_publication_preamble(config),
        "",
        r"\begin{document}",
        rf"\setpurhrunningauthor{{{_latex_text(config.author_name)}}}",
        r"\pagenumbering{arabic}",
        r"\pagestyle{fancy}",
        "% Corpus-level title page intentionally omitted in per-play PDF.",
        "% The visible title page is generated below by \\playtitlepage.",
    ]

    # Disabled intentionally: per-play PDFs must not start with the
    # corpus-level title page. Keeping these lines here makes it easy to
    # restore them later for a complete-corpus PDF.
    #
    # lines.extend(
    #     [
    #         rf"\title{{{_latex_text(config.corpus_title or 'Edition')}}}",
    #         rf"\author{{{_latex_text(config.author_name)}}}",
    #         r"\date{}",
    #         r"\frontmatter",
    #         r"\maketitle",
    #         r"\mainmatter",
    #     ]
    # )

   #  lines.extend(["", r"\mainmatter"])

    if config.general_intro_tei is not None:
        lines.extend(
            [
                "",
                "% GENERAL INTRO intentionally omitted from per-play PDF.",
                f"% GENERAL INTRO source: {_path_comment(config.general_intro_tei)}",
            ]
        )

        # Disabled intentionally: the general corpus introduction does not belong
        # in per-play publication PDFs. Keep this block here so it can be
        # restored easily if a future complete-corpus PDF is added.
        #
        # lines.extend(
        #     [
        #         "",
        #         rf"\setpurhrunningauthor{{{_latex_text(config.author_name)}}}",
        #         r"\setpurhrunningtitle{Introduction générale}",
        #         r"\publicationsection{Introduction générale}{Introduction générale}",
        #         f"% GENERAL INTRO: {_path_comment(config.general_intro_tei)}",
        #         _peritext_fragment(config.general_intro_tei),
        #     ]
        # )

    for play in config.plays:
        play_title = _play_title_from_tei(play.dramatic_xml_path)
        editor_credit = (
            f"Texte édité par {config.scientific_editor.strip()}."
            if config.scientific_editor.strip()
            else ""
        )
        dramatis_comment = _dramatis_comment(play.dramatis_xml_path, play.dramatic_xml_path)
        dramatis_fragment = _dramatis_fragment(play.dramatis_xml_path, play.dramatic_xml_path)
        lines.extend(
            [
                "",
                rf"\setpurhrunningauthor{{{_latex_text(config.author_name)}}}",
                rf"\setpurhrunningtitle{{{_latex_text(play_title)}}}",
                rf"\playtitlepage{{{_latex_text(play_title)}}}{{{_latex_text(config.author_name)}}}{{{_latex_text(editor_credit)}}}{{}}",
                f"% PLAY: {_latex_text(play_title)}",
            ]
        )

        if play.notice_xml_path is not None:
            lines.extend(
                [
                    "",
                    rf"\publicationsection{{Notice}}{{{_latex_text(play_title)}}}",
                    f"% NOTICE: {_path_comment(play.notice_xml_path)}",
                    _peritext_fragment(play.notice_xml_path),
                ]
            )

        if play.preface_xml_path is not None:
            lines.extend(
                [
                    "",
                    rf"\publicationsection{{Preface}}{{{_latex_text(play_title)}}}",
                    f"% PREFACE: {_path_comment(play.preface_xml_path)}",
                    _peritext_fragment(play.preface_xml_path),
                ]
            )

        if _has_dramatis_content(dramatis_fragment):
            lines.extend(
                [
                    "",
                    rf"\dramatissection{{{_latex_text(play_title)}}}",
                    dramatis_comment,
                    dramatis_fragment,
                ]
            )
        else:
            lines.extend(["", dramatis_comment, dramatis_fragment])

        lines.extend(
            [
                "",
                rf"\dramatictextsection{{{_latex_text(play_title)}}}",
                f"% DRAMATIC TEXT: {_path_comment(play.dramatic_xml_path)}",
                _dramatic_fragment(
                    play.dramatic_xml_path,
                    hide_minor_variants=config.hide_minor_variants_in_pdf,
                ),
            ]
        )

    lines.extend(["", r"\end{document}", ""])
    return "\n".join(lines)


def render_purh_publication_preamble(config: SitePublicationDialogConfig) -> str:
    running_title = _latex_text(config.corpus_title or "Publication")
    return "\n".join(
        [
            r"\documentclass[12pt,titlepage]{book}",
            r"\usepackage[",
            r"  paperwidth=155mm,",
            r"  paperheight=230mm,",
            r"  top=30mm,",
            r"  bottom=19mm,",
            r"  inner=23mm,",
            r"  outer=23mm,",
            r"  headheight=14pt,",
            r"  headsep=8mm,",
            r"  footskip=10mm",
            r"]{geometry}",
            r"\usepackage{fontspec}",
            r"\IfFontExistsTF{Chaparral Pro}",
            r"  {\setmainfont{Chaparral Pro}}",
            r"  {\IfFontExistsTF{TeX Gyre Pagella}{\setmainfont{TeX Gyre Pagella}}{\setmainfont{Latin Modern Roman}}}",
            r"\IfFontExistsTF{Josefin Sans}",
            r"  {\newfontfamily\PURHTitleFont{Josefin Sans}}",
            r"  {\IfFontExistsTF{TeX Gyre Heros}{\newfontfamily\PURHTitleFont{TeX Gyre Heros}}{\newfontfamily\PURHTitleFont{Latin Modern Sans}}}",
            r"\usepackage[french]{babel}",
            r"\usepackage{csquotes}",
            r"\usepackage{indentfirst}",
            r"\usepackage{xcolor}",
            r"\usepackage{array}",
            r"\usepackage{tabularx}",
            r"\usepackage{ragged2e}",
            r"\usepackage[nobottomtitles*]{titlesec}",
            r"\usepackage{titletoc}",
            r"\usepackage{fancyhdr}",
            r"\setcounter{secnumdepth}{0}",
            r"\clubpenalty=10000",
            r"\widowpenalty=10000",
            r"\displaywidowpenalty=10000",
            r"\interfootnotelinepenalty=10000",
            r"\renewcommand{\footnotesize}{\fontsize{7.4}{8.4}\selectfont}",
            r"\tolerance=2000",
            r"\emergencystretch=1em",
            r"\newcolumntype{Y}{>{\RaggedRight\arraybackslash\hspace{0pt}}X}",
            r"\renewcommand{\arraystretch}{1.15}",
            r"\addto\captionsfrench{%",
            r"  \renewcommand{\bibname}{Bibliographie}%",
            r"  \renewcommand{\contentsname}{Table des mati\`eres}%",
            r"}",
            r"\newcommand{\PURHRunningAuthor}{}",
            rf"\newcommand{{\PURHRunningTitle}}{{{running_title}}}",
            r"\newcommand{\setpurhrunningauthor}[1]{\gdef\PURHRunningAuthor{#1}}",
            r"\newcommand{\setpurhrunningtitle}[1]{\gdef\PURHRunningTitle{#1}}",
            r"\newcommand{\blankpage}{\thispagestyle{empty}\hbox{}\newpage}",
            r"\newcommand{\cleartorecto}{\clearpage\ifodd\value{page}\else\blankpage\fi}",
            r"\newcommand{\cleartoverso}{\clearpage\ifodd\value{page}\blankpage\fi}",
            r"\newcommand{\publicationsection}[2]{%",
            r"  \setpurhrunningtitle{#2}\cleartorecto\thispagestyle{empty}%",
            r"  {\PURHTitleFont\bfseries\huge #1\par}\vspace{2\baselineskip}%",
            r"}",
            r"\newcommand{\playtitlepage}[4]{%",
            r"  \setpurhrunningtitle{#1}\cleartorecto\thispagestyle{empty}%",
            r"  \begin{center}%",
            r"    \vspace*{0.28\textheight}%",
            r"    {\PURHTitleFont\bfseries\Huge #1\par}%",
            r"    \vspace{2\baselineskip}%",
            r"    {\Large #2\par}%",
            r"    \vspace{2\baselineskip}%",
            r"    \if\relax\detokenize{#3}\relax\else #3\par\fi%",
            r"    \if\relax\detokenize{#4}\relax\else #4\par\fi%",
            r"  \end{center}%",
            r"  \par%",
            r"}",
            r"\newcommand{\dramatissection}[1]{%",
            r"  \cleartoverso\setpurhrunningtitle{#1}\thispagestyle{empty}%",
            r"  {\PURHTitleFont\bfseries\huge Dramatis personae\par}\vspace{2\baselineskip}%",
            r"}",
            r"\newcommand{\dramatictextsection}[1]{%",
            r"  \cleartorecto\setpurhrunningtitle{#1}\thispagestyle{empty}%",
            r"}",
            r"\newenvironment{PURHDramaticText}{%",
            r"  \begingroup\fontsize{9.6}{11.4}\selectfont\RaggedRight\sloppy\setlength{\parindent}{0pt}%",
            r"}{%",
            r"  \par\endgroup%",
            r"}",
            r"\titleformat{\section}{\PURHTitleFont\bfseries\Large}{}{0pt}{}",
            r"\titleformat{\subsection}{\PURHTitleFont\bfseries\large}{}{0pt}{}",
            r"\pagestyle{fancy}",
            r"\fancyhf{}",
            r"% PURH running heads: even pages = page number + title; odd pages = author + page number.",
            r"\fancyhead[LE]{\thepage}",
            r"\fancyhead[RE]{\small\itshape\PURHRunningTitle}",
            r"\fancyhead[LO]{\small\itshape\PURHRunningAuthor}",
            r"\fancyhead[RO]{\thepage}",
            r"\renewcommand{\headrulewidth}{0pt}",
            r"\fancypagestyle{plain}{%",
            r"  \fancyhf{}%",
            r"  \renewcommand{\headrulewidth}{0pt}%",
            r"}",
            "% Publication PDF critical backend: Reledmac.",
            render_reledmac_support_preamble().rstrip(),
            _render_publication_reledmac_overrides(),
        ]
    )

def _render_publication_reledmac_overrides() -> str:
    return "\n".join(
        [
            r"% Publication PDF overrides for dramatic typography.",
            r"\renewenvironment{speech}{\par\begingroup}{\par\endgroup}",
            r"\renewcommand{\stage}[1]{%",
            r"  \par\addvspace{0.9\baselineskip}%",
            r"  {\centering\normalfont\fontsize{11}{12.6}\selectfont\scshape #1\par}%",
            r"  \addvspace{0.45\baselineskip}%",
            r"}",
            r"\renewcommand{\speaker}[1]{%",
            r"  \par\addvspace{0.6\baselineskip}%",
            r"  {\centering\normalfont\fontsize{10}{11.5}\selectfont\scshape #1\par}%",
            r"  \nobreak%",
            r"}",
            r"\renewcommand{\didas}[1]{%",
            r"  \par\addvspace{0.4\baselineskip}%",
            r"  {\centering\normalfont\small\itshape #1\par}%",
            r"  \addvspace{0.2\baselineskip}%",
            r"}",
        ]
    )

def _latex_text(value: str) -> str:
    return escape_latex_text(value.strip())


def _play_title_from_tei(path: Path) -> str:
    root = etree.parse(str(path)).getroot()
    title = root.xpath("string((.//*[local-name()='titleStmt']/*[local-name()='title'][normalize-space()][1])[1])")
    title_text = " ".join(str(title).split())
    return title_text or "Pièce sans titre"


def _path_comment(path: Path) -> str:
    return str(path.resolve())


def _peritext_fragment(path: Path) -> str:
    return tei_peritext_to_latex(path).rstrip()


def _dramatis_comment(dramatis_xml_path: Path | None, dramatic_xml_path: Path) -> str:
    if dramatis_xml_path is not None:
        return f"% DRAMATIS PERSONAE: {_path_comment(dramatis_xml_path)}"
    return f"% DRAMATIS PERSONAE: front of {_path_comment(dramatic_xml_path)}"


def _dramatis_fragment(dramatis_xml_path: Path | None, dramatic_xml_path: Path) -> str:
    source_path = dramatis_xml_path if dramatis_xml_path is not None else dramatic_xml_path
    return tei_castlist_to_latex(source_path).rstrip()


def _has_dramatis_content(fragment: str) -> bool:
    return bool(fragment.strip()) and "% DRAMATIS PERSONAE: no castList found." not in fragment


def _dramatic_fragment(dramatic_xml_path: Path, *, hide_minor_variants: bool = False) -> str:
    apparatus_policy = "hide_minor" if hide_minor_variants else "full"
    fragment = tei_to_reledmac(
        dramatic_xml_path,
        standalone=False,
        apparatus_policy=apparatus_policy,
        apparatus_numbering_policy="editorial",
    ).rstrip()
    if not fragment:
        return "\n".join(
            [
                r"\begin{PURHDramaticText}",
                r"\beginnumbering",
                r"\endnumbering",
                r"\end{PURHDramaticText}",
            ]
        )
    return "\n".join(
        [
            r"\begin{PURHDramaticText}",
            fragment,
            r"\end{PURHDramaticText}",
        ]
    )
